# Site settings
name: Benjamin Metzler
description: "I make things work"
url: "https://mtzlr.io"

blog_url: https://github.com/benjaminmetzler/TIL
github_username:  benjaminmetzler
linkedin_username: benjaminmetzler
mastodon: https://mas.to/@benjaminmetzler
public_key_url: https://mtzlr.io/gpg.txt

avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
avatar_img_path: "https://avatars0.githubusercontent.com/u/4074316"

front_img: yes
front_img_path: "imgs/bridge.jpg"
#front_img_path: "https://external.url/image.jpg"

favicon_img: no
#favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty

# other pages
include: ["gpg.txt", "/.well-known"]

