# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      sudo apt-get install ruby-full build-essential zlib1g-dev
      export GEM_HOME="$HOME/gems"
      export PATH="$HOME/gems/bin:$PATH"

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
